name: CI/CD

on:
  push:
    branches: 
        - develop
        - staging
        - master


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Cache Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-0  # increment to reset cache

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        version: 1.2.0b3
        virtualenvs-create: false
        installer-parallel: true

    - name: Cache poetry virtualenv
      uses: actions/cache@v3
      id: cached-python-env
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

    - name: Install python dependencies
      if: steps.cached-python-env.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
      
    - name: Test
      run: poetry run pytest

    - name: Install NodeJS for serverless framework
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'