name: CI/CD

on:
  push:
    branches: 
        - develop
        - staging
        - master


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'
    - run: poetry install
    - run: poetry run pytest