name: CI/CD

on:
  push:
    branches: 
        - develop
        - staging
        - master


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'poetry'
        
    - name: Install poetry
      run: pip install poetry==1.2.0b3
      
    - name: Install python dependencies
      run: poetry install
      
    - name: Test
      run: poetry run pytest
